[package]
name = "pkcs11"

version.workspace = true
edition.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[build-dependencies]
bindgen = "0.71"

[features]
pkcs11_3_2 = []
default = ["pkcs11_3_2"]
