USER_TARGET=libevercrypt.a
USER_CFLAGS=-Wno-unused
USER_C_FILES=Lib_Memzero0.c Lib_PrintBuffer.c Lib_RandomBuffer_System.c
ALL_C_FILES=Hacl_Hash_Base.c Hacl_Hash_SHA2.c Hacl_Hash_SHA1.c
ALL_H_FILES=Hacl_Hash_Base.h Hacl_Hash_SHA2.h Hacl_Hash_SHA1.h Hacl_IntTypes_Intrinsics.h Hacl_IntTypes_Intrinsics_128.h Hacl_Krmllib.h internal/Hacl_Hash_SHA2.h internal/Hacl_Hash_SHA1.h internal/Hacl_Krmllib.h internal/Hacl_SHA2_Types.h
