[package]
source-url = "https://github.com/latchset/%{name}/archive/%{commit}/%{name}-%{shortcommit}.tar.gz"
cargo-install-lib = true
cargo-install-bin = true

[features]
enable = ["standard", "dynamic", "nssdb"]

[requires]
build = ["openssl-devel"]
lib = ["openssl-libs"]
