[package]
source-url = "https://github.com/latchset/kryoptic/releases/download/v%{version}/%{name}-%{version}.tar.gz"
cargo-install-lib = true
cargo-install-bin = true

[features]
enable = ["nssdb", "pqc"]

[requires]
build = ["openssl-devel"]
lib = ["openssl-libs"]
