[package]
source-url = "https://github.com/latchset/kryoptic/archive/%{revision}.zip"
cargo-install-lib = true
cargo-install-bin = true

[features]
enable = ["standard", "dynamic", "nssdb"]

[requires]
build = ["openssl-devel"]
lib = ["openssl-libs"]
