---
name: Check Rust Format

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Check Style
    runs-on: ubuntu-22.04
    container: fedora:latest
    steps:
      - name: Get Date for DNF cache entry
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%V")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Store DNF cache
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/dnf
          key: ${{ runner.os }}-dnf-${{ steps.get-date.outputs.date }}

      - name: Install Dependencies
        run: |
          dnf -y install git rustfmt codespell make
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup
        if: ${{ github.event.pull_request.base.sha }}
        run: |
          git config --global --add safe.directory /__w/kryoptic/kryoptic
          git fetch origin main ${{ github.event.pull_request.base.sha }}
      - name: Run rustfmt
        run: |
          make fix-format
          LINES=`git diff -U0 --no-color |wc -l`; \
          if [ "$LINES" != "0" ]; then \
                echo "Rustfmt issues detected"; \
                git diff -U0 --no-color
                exit 1; \
          else \
                echo "Rustfmt is happy"; \
          fi
      - name: Codespell
        run: make check-spell
