---
name: Check Rust Format

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Check Style
    runs-on: ubuntu-22.04
    container: fedora:latest
    steps:
      - name: Install Dependencies
        run: |
          dnf -y install git rustfmt
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup
        if: ${{ github.event.pull_request.base.sha }}
        run: |
          git config --global --add safe.directory \
              /__w/kryoptic/kryoptic
          git fetch origin main ${{ github.event.pull_request.base.sha }}
      - name: Run rustfmt
        run: |
          rustfmt src/*.rs src/*/*.rs
          @lines=`git diff -U0 --no-color |wc -l`; \
          if [ "$$lines" != "0" ]; then \
                echo "Rustfmt issues detected"; \
                exit 1; \
          else \
                echo "Rustfmt is happy"; \
          fi
