---
name: Migrate Tool

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build:
    name: Migrate Tool
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        name: [standard]
    container: fedora:latest
    steps:
      - name: Get Date for DNF cache entry
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%V")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore DNF cache
        uses: actions/cache/restore@v4
        with:
          path: |
            /var/cache/libdnf5
          key: ${{ runner.os }}-dnf-${{ steps.get-date.outputs.date }}

      - name: Install Dependencies
        run: |
          dnf -y install git cargo clang-devel openssl-devel sqlite-devel opensc

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        run: |
          git config --global --add safe.directory /__w/kryoptic/kryoptic

      - name: Build & test
        run: |
          cargo build -vv
          src/tools/softhsm/test.sh

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Build logs ${{ matrix.name }}
          path: |
            target/debug/build/*/output
            target/i686-unknown-linux-gnu/debug/build/*/output
